
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CaseType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model CaseType
 * 
 */
export type CaseTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$CaseTypePayload>

export type AggregateCaseType = {
  _count: CaseTypeCountAggregateOutputType | null
  _avg: CaseTypeAvgAggregateOutputType | null
  _sum: CaseTypeSumAggregateOutputType | null
  _min: CaseTypeMinAggregateOutputType | null
  _max: CaseTypeMaxAggregateOutputType | null
}

export type CaseTypeAvgAggregateOutputType = {
  order: number | null
}

export type CaseTypeSumAggregateOutputType = {
  order: number | null
}

export type CaseTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  description: string | null
  color: string | null
  icon: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CaseTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  description: string | null
  color: string | null
  icon: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CaseTypeCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  description: number
  color: number
  icon: number
  order: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CaseTypeAvgAggregateInputType = {
  order?: true
}

export type CaseTypeSumAggregateInputType = {
  order?: true
}

export type CaseTypeMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  color?: true
  icon?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type CaseTypeMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  color?: true
  icon?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type CaseTypeCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  color?: true
  icon?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CaseTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaseType to aggregate.
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaseTypes to fetch.
   */
  orderBy?: Prisma.CaseTypeOrderByWithRelationInput | Prisma.CaseTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CaseTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaseTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaseTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CaseTypes
  **/
  _count?: true | CaseTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CaseTypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CaseTypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CaseTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CaseTypeMaxAggregateInputType
}

export type GetCaseTypeAggregateType<T extends CaseTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateCaseType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCaseType[P]>
    : Prisma.GetScalarType<T[P], AggregateCaseType[P]>
}




export type CaseTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaseTypeWhereInput
  orderBy?: Prisma.CaseTypeOrderByWithAggregationInput | Prisma.CaseTypeOrderByWithAggregationInput[]
  by: Prisma.CaseTypeScalarFieldEnum[] | Prisma.CaseTypeScalarFieldEnum
  having?: Prisma.CaseTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaseTypeCountAggregateInputType | true
  _avg?: CaseTypeAvgAggregateInputType
  _sum?: CaseTypeSumAggregateInputType
  _min?: CaseTypeMinAggregateInputType
  _max?: CaseTypeMaxAggregateInputType
}

export type CaseTypeGroupByOutputType = {
  id: string
  name: string
  slug: string
  description: string | null
  color: string | null
  icon: string | null
  order: number | null
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: CaseTypeCountAggregateOutputType | null
  _avg: CaseTypeAvgAggregateOutputType | null
  _sum: CaseTypeSumAggregateOutputType | null
  _min: CaseTypeMinAggregateOutputType | null
  _max: CaseTypeMaxAggregateOutputType | null
}

type GetCaseTypeGroupByPayload<T extends CaseTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaseTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CaseTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CaseTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CaseTypeGroupByOutputType[P]>
      }
    >
  >



export type CaseTypeWhereInput = {
  AND?: Prisma.CaseTypeWhereInput | Prisma.CaseTypeWhereInput[]
  OR?: Prisma.CaseTypeWhereInput[]
  NOT?: Prisma.CaseTypeWhereInput | Prisma.CaseTypeWhereInput[]
  id?: Prisma.StringFilter<"CaseType"> | string
  name?: Prisma.StringFilter<"CaseType"> | string
  slug?: Prisma.StringFilter<"CaseType"> | string
  description?: Prisma.StringNullableFilter<"CaseType"> | string | null
  color?: Prisma.StringNullableFilter<"CaseType"> | string | null
  icon?: Prisma.StringNullableFilter<"CaseType"> | string | null
  order?: Prisma.IntNullableFilter<"CaseType"> | number | null
  active?: Prisma.BoolFilter<"CaseType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"CaseType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CaseType"> | Date | string
  legalCases?: Prisma.LegalCaseListRelationFilter
}

export type CaseTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  legalCases?: Prisma.LegalCaseOrderByRelationAggregateInput
}

export type CaseTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  slug?: string
  AND?: Prisma.CaseTypeWhereInput | Prisma.CaseTypeWhereInput[]
  OR?: Prisma.CaseTypeWhereInput[]
  NOT?: Prisma.CaseTypeWhereInput | Prisma.CaseTypeWhereInput[]
  description?: Prisma.StringNullableFilter<"CaseType"> | string | null
  color?: Prisma.StringNullableFilter<"CaseType"> | string | null
  icon?: Prisma.StringNullableFilter<"CaseType"> | string | null
  order?: Prisma.IntNullableFilter<"CaseType"> | number | null
  active?: Prisma.BoolFilter<"CaseType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"CaseType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CaseType"> | Date | string
  legalCases?: Prisma.LegalCaseListRelationFilter
}, "id" | "name" | "slug">

export type CaseTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CaseTypeCountOrderByAggregateInput
  _avg?: Prisma.CaseTypeAvgOrderByAggregateInput
  _max?: Prisma.CaseTypeMaxOrderByAggregateInput
  _min?: Prisma.CaseTypeMinOrderByAggregateInput
  _sum?: Prisma.CaseTypeSumOrderByAggregateInput
}

export type CaseTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaseTypeScalarWhereWithAggregatesInput | Prisma.CaseTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaseTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaseTypeScalarWhereWithAggregatesInput | Prisma.CaseTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CaseType"> | string
  name?: Prisma.StringWithAggregatesFilter<"CaseType"> | string
  slug?: Prisma.StringWithAggregatesFilter<"CaseType"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"CaseType"> | string | null
  color?: Prisma.StringNullableWithAggregatesFilter<"CaseType"> | string | null
  icon?: Prisma.StringNullableWithAggregatesFilter<"CaseType"> | string | null
  order?: Prisma.IntNullableWithAggregatesFilter<"CaseType"> | number | null
  active?: Prisma.BoolWithAggregatesFilter<"CaseType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CaseType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CaseType"> | Date | string
}

export type CaseTypeCreateInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  icon?: string | null
  order?: number | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  legalCases?: Prisma.LegalCaseCreateNestedManyWithoutCaseTypeInput
}

export type CaseTypeUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  icon?: string | null
  order?: number | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  legalCases?: Prisma.LegalCaseUncheckedCreateNestedManyWithoutCaseTypeInput
}

export type CaseTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  legalCases?: Prisma.LegalCaseUpdateManyWithoutCaseTypeNestedInput
}

export type CaseTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  legalCases?: Prisma.LegalCaseUncheckedUpdateManyWithoutCaseTypeNestedInput
}

export type CaseTypeCreateManyInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  icon?: string | null
  order?: number | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaseTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseTypeNullableScalarRelationFilter = {
  is?: Prisma.CaseTypeWhereInput | null
  isNot?: Prisma.CaseTypeWhereInput | null
}

export type CaseTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaseTypeAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CaseTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaseTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  color?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CaseTypeSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CaseTypeCreateNestedOneWithoutLegalCasesInput = {
  create?: Prisma.XOR<Prisma.CaseTypeCreateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedCreateWithoutLegalCasesInput>
  connectOrCreate?: Prisma.CaseTypeCreateOrConnectWithoutLegalCasesInput
  connect?: Prisma.CaseTypeWhereUniqueInput
}

export type CaseTypeUpdateOneWithoutLegalCasesNestedInput = {
  create?: Prisma.XOR<Prisma.CaseTypeCreateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedCreateWithoutLegalCasesInput>
  connectOrCreate?: Prisma.CaseTypeCreateOrConnectWithoutLegalCasesInput
  upsert?: Prisma.CaseTypeUpsertWithoutLegalCasesInput
  disconnect?: Prisma.CaseTypeWhereInput | boolean
  delete?: Prisma.CaseTypeWhereInput | boolean
  connect?: Prisma.CaseTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CaseTypeUpdateToOneWithWhereWithoutLegalCasesInput, Prisma.CaseTypeUpdateWithoutLegalCasesInput>, Prisma.CaseTypeUncheckedUpdateWithoutLegalCasesInput>
}

export type CaseTypeCreateWithoutLegalCasesInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  icon?: string | null
  order?: number | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaseTypeUncheckedCreateWithoutLegalCasesInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  color?: string | null
  icon?: string | null
  order?: number | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaseTypeCreateOrConnectWithoutLegalCasesInput = {
  where: Prisma.CaseTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.CaseTypeCreateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedCreateWithoutLegalCasesInput>
}

export type CaseTypeUpsertWithoutLegalCasesInput = {
  update: Prisma.XOR<Prisma.CaseTypeUpdateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedUpdateWithoutLegalCasesInput>
  create: Prisma.XOR<Prisma.CaseTypeCreateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedCreateWithoutLegalCasesInput>
  where?: Prisma.CaseTypeWhereInput
}

export type CaseTypeUpdateToOneWithWhereWithoutLegalCasesInput = {
  where?: Prisma.CaseTypeWhereInput
  data: Prisma.XOR<Prisma.CaseTypeUpdateWithoutLegalCasesInput, Prisma.CaseTypeUncheckedUpdateWithoutLegalCasesInput>
}

export type CaseTypeUpdateWithoutLegalCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseTypeUncheckedUpdateWithoutLegalCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CaseTypeCountOutputType
 */

export type CaseTypeCountOutputType = {
  legalCases: number
}

export type CaseTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  legalCases?: boolean | CaseTypeCountOutputTypeCountLegalCasesArgs
}

/**
 * CaseTypeCountOutputType without action
 */
export type CaseTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseTypeCountOutputType
   */
  select?: Prisma.CaseTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CaseTypeCountOutputType without action
 */
export type CaseTypeCountOutputTypeCountLegalCasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LegalCaseWhereInput
}


export type CaseTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  color?: boolean
  icon?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  legalCases?: boolean | Prisma.CaseType$legalCasesArgs<ExtArgs>
  _count?: boolean | Prisma.CaseTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["caseType"]>

export type CaseTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  color?: boolean
  icon?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["caseType"]>

export type CaseTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  color?: boolean
  icon?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["caseType"]>

export type CaseTypeSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  color?: boolean
  icon?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CaseTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "description" | "color" | "icon" | "order" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["caseType"]>
export type CaseTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  legalCases?: boolean | Prisma.CaseType$legalCasesArgs<ExtArgs>
  _count?: boolean | Prisma.CaseTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type CaseTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CaseTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CaseTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CaseType"
  objects: {
    legalCases: Prisma.$LegalCasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    description: string | null
    color: string | null
    icon: string | null
    order: number | null
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["caseType"]>
  composites: {}
}

export type CaseTypeGetPayload<S extends boolean | null | undefined | CaseTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CaseTypePayload, S>

export type CaseTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CaseTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CaseTypeCountAggregateInputType | true
  }

export interface CaseTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CaseType'], meta: { name: 'CaseType' } }
  /**
   * Find zero or one CaseType that matches the filter.
   * @param {CaseTypeFindUniqueArgs} args - Arguments to find a CaseType
   * @example
   * // Get one CaseType
   * const caseType = await prisma.caseType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaseTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, CaseTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CaseType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaseTypeFindUniqueOrThrowArgs} args - Arguments to find a CaseType
   * @example
   * // Get one CaseType
   * const caseType = await prisma.caseType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaseTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CaseTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaseType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeFindFirstArgs} args - Arguments to find a CaseType
   * @example
   * // Get one CaseType
   * const caseType = await prisma.caseType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaseTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, CaseTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CaseType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeFindFirstOrThrowArgs} args - Arguments to find a CaseType
   * @example
   * // Get one CaseType
   * const caseType = await prisma.caseType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaseTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CaseTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CaseTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CaseTypes
   * const caseTypes = await prisma.caseType.findMany()
   * 
   * // Get first 10 CaseTypes
   * const caseTypes = await prisma.caseType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const caseTypeWithIdOnly = await prisma.caseType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CaseTypeFindManyArgs>(args?: Prisma.SelectSubset<T, CaseTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CaseType.
   * @param {CaseTypeCreateArgs} args - Arguments to create a CaseType.
   * @example
   * // Create one CaseType
   * const CaseType = await prisma.caseType.create({
   *   data: {
   *     // ... data to create a CaseType
   *   }
   * })
   * 
   */
  create<T extends CaseTypeCreateArgs>(args: Prisma.SelectSubset<T, CaseTypeCreateArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CaseTypes.
   * @param {CaseTypeCreateManyArgs} args - Arguments to create many CaseTypes.
   * @example
   * // Create many CaseTypes
   * const caseType = await prisma.caseType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CaseTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, CaseTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CaseTypes and returns the data saved in the database.
   * @param {CaseTypeCreateManyAndReturnArgs} args - Arguments to create many CaseTypes.
   * @example
   * // Create many CaseTypes
   * const caseType = await prisma.caseType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CaseTypes and only return the `id`
   * const caseTypeWithIdOnly = await prisma.caseType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CaseTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CaseTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CaseType.
   * @param {CaseTypeDeleteArgs} args - Arguments to delete one CaseType.
   * @example
   * // Delete one CaseType
   * const CaseType = await prisma.caseType.delete({
   *   where: {
   *     // ... filter to delete one CaseType
   *   }
   * })
   * 
   */
  delete<T extends CaseTypeDeleteArgs>(args: Prisma.SelectSubset<T, CaseTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CaseType.
   * @param {CaseTypeUpdateArgs} args - Arguments to update one CaseType.
   * @example
   * // Update one CaseType
   * const caseType = await prisma.caseType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CaseTypeUpdateArgs>(args: Prisma.SelectSubset<T, CaseTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CaseTypes.
   * @param {CaseTypeDeleteManyArgs} args - Arguments to filter CaseTypes to delete.
   * @example
   * // Delete a few CaseTypes
   * const { count } = await prisma.caseType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CaseTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CaseTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaseTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CaseTypes
   * const caseType = await prisma.caseType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CaseTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, CaseTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CaseTypes and returns the data updated in the database.
   * @param {CaseTypeUpdateManyAndReturnArgs} args - Arguments to update many CaseTypes.
   * @example
   * // Update many CaseTypes
   * const caseType = await prisma.caseType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CaseTypes and only return the `id`
   * const caseTypeWithIdOnly = await prisma.caseType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CaseTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CaseTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CaseType.
   * @param {CaseTypeUpsertArgs} args - Arguments to update or create a CaseType.
   * @example
   * // Update or create a CaseType
   * const caseType = await prisma.caseType.upsert({
   *   create: {
   *     // ... data to create a CaseType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CaseType we want to update
   *   }
   * })
   */
  upsert<T extends CaseTypeUpsertArgs>(args: Prisma.SelectSubset<T, CaseTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CaseTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeCountArgs} args - Arguments to filter CaseTypes to count.
   * @example
   * // Count the number of CaseTypes
   * const count = await prisma.caseType.count({
   *   where: {
   *     // ... the filter for the CaseTypes we want to count
   *   }
   * })
  **/
  count<T extends CaseTypeCountArgs>(
    args?: Prisma.Subset<T, CaseTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CaseTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CaseType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CaseTypeAggregateArgs>(args: Prisma.Subset<T, CaseTypeAggregateArgs>): Prisma.PrismaPromise<GetCaseTypeAggregateType<T>>

  /**
   * Group by CaseType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CaseTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaseTypeGroupByArgs['orderBy'] }
      : { orderBy?: CaseTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CaseTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCaseTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CaseType model
 */
readonly fields: CaseTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CaseType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaseTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  legalCases<T extends Prisma.CaseType$legalCasesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CaseType$legalCasesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CaseType model
 */
export interface CaseTypeFieldRefs {
  readonly id: Prisma.FieldRef<"CaseType", 'String'>
  readonly name: Prisma.FieldRef<"CaseType", 'String'>
  readonly slug: Prisma.FieldRef<"CaseType", 'String'>
  readonly description: Prisma.FieldRef<"CaseType", 'String'>
  readonly color: Prisma.FieldRef<"CaseType", 'String'>
  readonly icon: Prisma.FieldRef<"CaseType", 'String'>
  readonly order: Prisma.FieldRef<"CaseType", 'Int'>
  readonly active: Prisma.FieldRef<"CaseType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"CaseType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CaseType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CaseType findUnique
 */
export type CaseTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter, which CaseType to fetch.
   */
  where: Prisma.CaseTypeWhereUniqueInput
}

/**
 * CaseType findUniqueOrThrow
 */
export type CaseTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter, which CaseType to fetch.
   */
  where: Prisma.CaseTypeWhereUniqueInput
}

/**
 * CaseType findFirst
 */
export type CaseTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter, which CaseType to fetch.
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaseTypes to fetch.
   */
  orderBy?: Prisma.CaseTypeOrderByWithRelationInput | Prisma.CaseTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaseTypes.
   */
  cursor?: Prisma.CaseTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaseTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaseTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaseTypes.
   */
  distinct?: Prisma.CaseTypeScalarFieldEnum | Prisma.CaseTypeScalarFieldEnum[]
}

/**
 * CaseType findFirstOrThrow
 */
export type CaseTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter, which CaseType to fetch.
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaseTypes to fetch.
   */
  orderBy?: Prisma.CaseTypeOrderByWithRelationInput | Prisma.CaseTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CaseTypes.
   */
  cursor?: Prisma.CaseTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaseTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaseTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CaseTypes.
   */
  distinct?: Prisma.CaseTypeScalarFieldEnum | Prisma.CaseTypeScalarFieldEnum[]
}

/**
 * CaseType findMany
 */
export type CaseTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter, which CaseTypes to fetch.
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CaseTypes to fetch.
   */
  orderBy?: Prisma.CaseTypeOrderByWithRelationInput | Prisma.CaseTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CaseTypes.
   */
  cursor?: Prisma.CaseTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CaseTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CaseTypes.
   */
  skip?: number
  distinct?: Prisma.CaseTypeScalarFieldEnum | Prisma.CaseTypeScalarFieldEnum[]
}

/**
 * CaseType create
 */
export type CaseTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a CaseType.
   */
  data: Prisma.XOR<Prisma.CaseTypeCreateInput, Prisma.CaseTypeUncheckedCreateInput>
}

/**
 * CaseType createMany
 */
export type CaseTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CaseTypes.
   */
  data: Prisma.CaseTypeCreateManyInput | Prisma.CaseTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaseType createManyAndReturn
 */
export type CaseTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * The data used to create many CaseTypes.
   */
  data: Prisma.CaseTypeCreateManyInput | Prisma.CaseTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CaseType update
 */
export type CaseTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a CaseType.
   */
  data: Prisma.XOR<Prisma.CaseTypeUpdateInput, Prisma.CaseTypeUncheckedUpdateInput>
  /**
   * Choose, which CaseType to update.
   */
  where: Prisma.CaseTypeWhereUniqueInput
}

/**
 * CaseType updateMany
 */
export type CaseTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CaseTypes.
   */
  data: Prisma.XOR<Prisma.CaseTypeUpdateManyMutationInput, Prisma.CaseTypeUncheckedUpdateManyInput>
  /**
   * Filter which CaseTypes to update
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * Limit how many CaseTypes to update.
   */
  limit?: number
}

/**
 * CaseType updateManyAndReturn
 */
export type CaseTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * The data used to update CaseTypes.
   */
  data: Prisma.XOR<Prisma.CaseTypeUpdateManyMutationInput, Prisma.CaseTypeUncheckedUpdateManyInput>
  /**
   * Filter which CaseTypes to update
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * Limit how many CaseTypes to update.
   */
  limit?: number
}

/**
 * CaseType upsert
 */
export type CaseTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the CaseType to update in case it exists.
   */
  where: Prisma.CaseTypeWhereUniqueInput
  /**
   * In case the CaseType found by the `where` argument doesn't exist, create a new CaseType with this data.
   */
  create: Prisma.XOR<Prisma.CaseTypeCreateInput, Prisma.CaseTypeUncheckedCreateInput>
  /**
   * In case the CaseType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaseTypeUpdateInput, Prisma.CaseTypeUncheckedUpdateInput>
}

/**
 * CaseType delete
 */
export type CaseTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  /**
   * Filter which CaseType to delete.
   */
  where: Prisma.CaseTypeWhereUniqueInput
}

/**
 * CaseType deleteMany
 */
export type CaseTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CaseTypes to delete
   */
  where?: Prisma.CaseTypeWhereInput
  /**
   * Limit how many CaseTypes to delete.
   */
  limit?: number
}

/**
 * CaseType.legalCases
 */
export type CaseType$legalCasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  where?: Prisma.LegalCaseWhereInput
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  cursor?: Prisma.LegalCaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LegalCaseScalarFieldEnum | Prisma.LegalCaseScalarFieldEnum[]
}

/**
 * CaseType without action
 */
export type CaseTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
}
