
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Court` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Court
 * 
 */
export type CourtModel = runtime.Types.Result.DefaultSelection<Prisma.$CourtPayload>

export type AggregateCourt = {
  _count: CourtCountAggregateOutputType | null
  _min: CourtMinAggregateOutputType | null
  _max: CourtMaxAggregateOutputType | null
}

export type CourtMinAggregateOutputType = {
  id: string | null
  name: string | null
  type: $Enums.CourtType | null
  jurisdiction: $Enums.Jurisdiction | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CourtMaxAggregateOutputType = {
  id: string | null
  name: string | null
  type: $Enums.CourtType | null
  jurisdiction: $Enums.Jurisdiction | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CourtCountAggregateOutputType = {
  id: number
  name: number
  type: number
  jurisdiction: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CourtMinAggregateInputType = {
  id?: true
  name?: true
  type?: true
  jurisdiction?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type CourtMaxAggregateInputType = {
  id?: true
  name?: true
  type?: true
  jurisdiction?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type CourtCountAggregateInputType = {
  id?: true
  name?: true
  type?: true
  jurisdiction?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CourtAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Court to aggregate.
   */
  where?: Prisma.CourtWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courts to fetch.
   */
  orderBy?: Prisma.CourtOrderByWithRelationInput | Prisma.CourtOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CourtWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Courts
  **/
  _count?: true | CourtCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CourtMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CourtMaxAggregateInputType
}

export type GetCourtAggregateType<T extends CourtAggregateArgs> = {
      [P in keyof T & keyof AggregateCourt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourt[P]>
    : Prisma.GetScalarType<T[P], AggregateCourt[P]>
}




export type CourtGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CourtWhereInput
  orderBy?: Prisma.CourtOrderByWithAggregationInput | Prisma.CourtOrderByWithAggregationInput[]
  by: Prisma.CourtScalarFieldEnum[] | Prisma.CourtScalarFieldEnum
  having?: Prisma.CourtScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CourtCountAggregateInputType | true
  _min?: CourtMinAggregateInputType
  _max?: CourtMaxAggregateInputType
}

export type CourtGroupByOutputType = {
  id: string
  name: string
  type: $Enums.CourtType | null
  jurisdiction: $Enums.Jurisdiction | null
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: CourtCountAggregateOutputType | null
  _min: CourtMinAggregateOutputType | null
  _max: CourtMaxAggregateOutputType | null
}

type GetCourtGroupByPayload<T extends CourtGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CourtGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CourtGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CourtGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CourtGroupByOutputType[P]>
      }
    >
  >



export type CourtWhereInput = {
  AND?: Prisma.CourtWhereInput | Prisma.CourtWhereInput[]
  OR?: Prisma.CourtWhereInput[]
  NOT?: Prisma.CourtWhereInput | Prisma.CourtWhereInput[]
  id?: Prisma.StringFilter<"Court"> | string
  name?: Prisma.StringFilter<"Court"> | string
  type?: Prisma.EnumCourtTypeNullableFilter<"Court"> | $Enums.CourtType | null
  jurisdiction?: Prisma.EnumJurisdictionNullableFilter<"Court"> | $Enums.Jurisdiction | null
  description?: Prisma.StringNullableFilter<"Court"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Court"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Court"> | Date | string
  cases?: Prisma.LegalCaseListRelationFilter
}

export type CourtOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  jurisdiction?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  cases?: Prisma.LegalCaseOrderByRelationAggregateInput
}

export type CourtWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.CourtWhereInput | Prisma.CourtWhereInput[]
  OR?: Prisma.CourtWhereInput[]
  NOT?: Prisma.CourtWhereInput | Prisma.CourtWhereInput[]
  type?: Prisma.EnumCourtTypeNullableFilter<"Court"> | $Enums.CourtType | null
  jurisdiction?: Prisma.EnumJurisdictionNullableFilter<"Court"> | $Enums.Jurisdiction | null
  description?: Prisma.StringNullableFilter<"Court"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Court"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Court"> | Date | string
  cases?: Prisma.LegalCaseListRelationFilter
}, "id" | "name">

export type CourtOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  jurisdiction?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CourtCountOrderByAggregateInput
  _max?: Prisma.CourtMaxOrderByAggregateInput
  _min?: Prisma.CourtMinOrderByAggregateInput
}

export type CourtScalarWhereWithAggregatesInput = {
  AND?: Prisma.CourtScalarWhereWithAggregatesInput | Prisma.CourtScalarWhereWithAggregatesInput[]
  OR?: Prisma.CourtScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CourtScalarWhereWithAggregatesInput | Prisma.CourtScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Court"> | string
  name?: Prisma.StringWithAggregatesFilter<"Court"> | string
  type?: Prisma.EnumCourtTypeNullableWithAggregatesFilter<"Court"> | $Enums.CourtType | null
  jurisdiction?: Prisma.EnumJurisdictionNullableWithAggregatesFilter<"Court"> | $Enums.Jurisdiction | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Court"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Court"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Court"> | Date | string
}

export type CourtCreateInput = {
  id?: string
  name: string
  type?: $Enums.CourtType | null
  jurisdiction?: $Enums.Jurisdiction | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cases?: Prisma.LegalCaseCreateNestedManyWithoutCourtInput
}

export type CourtUncheckedCreateInput = {
  id?: string
  name: string
  type?: $Enums.CourtType | null
  jurisdiction?: $Enums.Jurisdiction | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cases?: Prisma.LegalCaseUncheckedCreateNestedManyWithoutCourtInput
}

export type CourtUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cases?: Prisma.LegalCaseUpdateManyWithoutCourtNestedInput
}

export type CourtUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cases?: Prisma.LegalCaseUncheckedUpdateManyWithoutCourtNestedInput
}

export type CourtCreateManyInput = {
  id?: string
  name: string
  type?: $Enums.CourtType | null
  jurisdiction?: $Enums.Jurisdiction | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourtUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourtUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourtNullableScalarRelationFilter = {
  is?: Prisma.CourtWhereInput | null
  isNot?: Prisma.CourtWhereInput | null
}

export type CourtCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourtMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourtMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CourtCreateNestedOneWithoutCasesInput = {
  create?: Prisma.XOR<Prisma.CourtCreateWithoutCasesInput, Prisma.CourtUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.CourtCreateOrConnectWithoutCasesInput
  connect?: Prisma.CourtWhereUniqueInput
}

export type CourtUpdateOneWithoutCasesNestedInput = {
  create?: Prisma.XOR<Prisma.CourtCreateWithoutCasesInput, Prisma.CourtUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.CourtCreateOrConnectWithoutCasesInput
  upsert?: Prisma.CourtUpsertWithoutCasesInput
  disconnect?: Prisma.CourtWhereInput | boolean
  delete?: Prisma.CourtWhereInput | boolean
  connect?: Prisma.CourtWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CourtUpdateToOneWithWhereWithoutCasesInput, Prisma.CourtUpdateWithoutCasesInput>, Prisma.CourtUncheckedUpdateWithoutCasesInput>
}

export type NullableEnumCourtTypeFieldUpdateOperationsInput = {
  set?: $Enums.CourtType | null
}

export type CourtCreateWithoutCasesInput = {
  id?: string
  name: string
  type?: $Enums.CourtType | null
  jurisdiction?: $Enums.Jurisdiction | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourtUncheckedCreateWithoutCasesInput = {
  id?: string
  name: string
  type?: $Enums.CourtType | null
  jurisdiction?: $Enums.Jurisdiction | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CourtCreateOrConnectWithoutCasesInput = {
  where: Prisma.CourtWhereUniqueInput
  create: Prisma.XOR<Prisma.CourtCreateWithoutCasesInput, Prisma.CourtUncheckedCreateWithoutCasesInput>
}

export type CourtUpsertWithoutCasesInput = {
  update: Prisma.XOR<Prisma.CourtUpdateWithoutCasesInput, Prisma.CourtUncheckedUpdateWithoutCasesInput>
  create: Prisma.XOR<Prisma.CourtCreateWithoutCasesInput, Prisma.CourtUncheckedCreateWithoutCasesInput>
  where?: Prisma.CourtWhereInput
}

export type CourtUpdateToOneWithWhereWithoutCasesInput = {
  where?: Prisma.CourtWhereInput
  data: Prisma.XOR<Prisma.CourtUpdateWithoutCasesInput, Prisma.CourtUncheckedUpdateWithoutCasesInput>
}

export type CourtUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CourtUncheckedUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableEnumCourtTypeFieldUpdateOperationsInput | $Enums.CourtType | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CourtCountOutputType
 */

export type CourtCountOutputType = {
  cases: number
}

export type CourtCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cases?: boolean | CourtCountOutputTypeCountCasesArgs
}

/**
 * CourtCountOutputType without action
 */
export type CourtCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourtCountOutputType
   */
  select?: Prisma.CourtCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CourtCountOutputType without action
 */
export type CourtCountOutputTypeCountCasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LegalCaseWhereInput
}


export type CourtSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  jurisdiction?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cases?: boolean | Prisma.Court$casesArgs<ExtArgs>
  _count?: boolean | Prisma.CourtCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["court"]>

export type CourtSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  jurisdiction?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["court"]>

export type CourtSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  jurisdiction?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["court"]>

export type CourtSelectScalar = {
  id?: boolean
  name?: boolean
  type?: boolean
  jurisdiction?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CourtOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "type" | "jurisdiction" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["court"]>
export type CourtInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cases?: boolean | Prisma.Court$casesArgs<ExtArgs>
  _count?: boolean | Prisma.CourtCountOutputTypeDefaultArgs<ExtArgs>
}
export type CourtIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CourtIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CourtPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Court"
  objects: {
    cases: Prisma.$LegalCasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    type: $Enums.CourtType | null
    jurisdiction: $Enums.Jurisdiction | null
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["court"]>
  composites: {}
}

export type CourtGetPayload<S extends boolean | null | undefined | CourtDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CourtPayload, S>

export type CourtCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CourtFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CourtCountAggregateInputType | true
  }

export interface CourtDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Court'], meta: { name: 'Court' } }
  /**
   * Find zero or one Court that matches the filter.
   * @param {CourtFindUniqueArgs} args - Arguments to find a Court
   * @example
   * // Get one Court
   * const court = await prisma.court.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CourtFindUniqueArgs>(args: Prisma.SelectSubset<T, CourtFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Court that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CourtFindUniqueOrThrowArgs} args - Arguments to find a Court
   * @example
   * // Get one Court
   * const court = await prisma.court.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CourtFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CourtFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Court that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtFindFirstArgs} args - Arguments to find a Court
   * @example
   * // Get one Court
   * const court = await prisma.court.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CourtFindFirstArgs>(args?: Prisma.SelectSubset<T, CourtFindFirstArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Court that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtFindFirstOrThrowArgs} args - Arguments to find a Court
   * @example
   * // Get one Court
   * const court = await prisma.court.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CourtFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CourtFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Courts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Courts
   * const courts = await prisma.court.findMany()
   * 
   * // Get first 10 Courts
   * const courts = await prisma.court.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const courtWithIdOnly = await prisma.court.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CourtFindManyArgs>(args?: Prisma.SelectSubset<T, CourtFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Court.
   * @param {CourtCreateArgs} args - Arguments to create a Court.
   * @example
   * // Create one Court
   * const Court = await prisma.court.create({
   *   data: {
   *     // ... data to create a Court
   *   }
   * })
   * 
   */
  create<T extends CourtCreateArgs>(args: Prisma.SelectSubset<T, CourtCreateArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Courts.
   * @param {CourtCreateManyArgs} args - Arguments to create many Courts.
   * @example
   * // Create many Courts
   * const court = await prisma.court.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CourtCreateManyArgs>(args?: Prisma.SelectSubset<T, CourtCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Courts and returns the data saved in the database.
   * @param {CourtCreateManyAndReturnArgs} args - Arguments to create many Courts.
   * @example
   * // Create many Courts
   * const court = await prisma.court.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Courts and only return the `id`
   * const courtWithIdOnly = await prisma.court.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CourtCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CourtCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Court.
   * @param {CourtDeleteArgs} args - Arguments to delete one Court.
   * @example
   * // Delete one Court
   * const Court = await prisma.court.delete({
   *   where: {
   *     // ... filter to delete one Court
   *   }
   * })
   * 
   */
  delete<T extends CourtDeleteArgs>(args: Prisma.SelectSubset<T, CourtDeleteArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Court.
   * @param {CourtUpdateArgs} args - Arguments to update one Court.
   * @example
   * // Update one Court
   * const court = await prisma.court.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CourtUpdateArgs>(args: Prisma.SelectSubset<T, CourtUpdateArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Courts.
   * @param {CourtDeleteManyArgs} args - Arguments to filter Courts to delete.
   * @example
   * // Delete a few Courts
   * const { count } = await prisma.court.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CourtDeleteManyArgs>(args?: Prisma.SelectSubset<T, CourtDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Courts
   * const court = await prisma.court.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CourtUpdateManyArgs>(args: Prisma.SelectSubset<T, CourtUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courts and returns the data updated in the database.
   * @param {CourtUpdateManyAndReturnArgs} args - Arguments to update many Courts.
   * @example
   * // Update many Courts
   * const court = await prisma.court.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Courts and only return the `id`
   * const courtWithIdOnly = await prisma.court.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CourtUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CourtUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Court.
   * @param {CourtUpsertArgs} args - Arguments to update or create a Court.
   * @example
   * // Update or create a Court
   * const court = await prisma.court.upsert({
   *   create: {
   *     // ... data to create a Court
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Court we want to update
   *   }
   * })
   */
  upsert<T extends CourtUpsertArgs>(args: Prisma.SelectSubset<T, CourtUpsertArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Courts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtCountArgs} args - Arguments to filter Courts to count.
   * @example
   * // Count the number of Courts
   * const count = await prisma.court.count({
   *   where: {
   *     // ... the filter for the Courts we want to count
   *   }
   * })
  **/
  count<T extends CourtCountArgs>(
    args?: Prisma.Subset<T, CourtCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CourtCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Court.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CourtAggregateArgs>(args: Prisma.Subset<T, CourtAggregateArgs>): Prisma.PrismaPromise<GetCourtAggregateType<T>>

  /**
   * Group by Court.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourtGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CourtGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CourtGroupByArgs['orderBy'] }
      : { orderBy?: CourtGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CourtGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCourtGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Court model
 */
readonly fields: CourtFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Court.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CourtClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cases<T extends Prisma.Court$casesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Court$casesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Court model
 */
export interface CourtFieldRefs {
  readonly id: Prisma.FieldRef<"Court", 'String'>
  readonly name: Prisma.FieldRef<"Court", 'String'>
  readonly type: Prisma.FieldRef<"Court", 'CourtType'>
  readonly jurisdiction: Prisma.FieldRef<"Court", 'Jurisdiction'>
  readonly description: Prisma.FieldRef<"Court", 'String'>
  readonly createdAt: Prisma.FieldRef<"Court", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Court", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Court findUnique
 */
export type CourtFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter, which Court to fetch.
   */
  where: Prisma.CourtWhereUniqueInput
}

/**
 * Court findUniqueOrThrow
 */
export type CourtFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter, which Court to fetch.
   */
  where: Prisma.CourtWhereUniqueInput
}

/**
 * Court findFirst
 */
export type CourtFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter, which Court to fetch.
   */
  where?: Prisma.CourtWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courts to fetch.
   */
  orderBy?: Prisma.CourtOrderByWithRelationInput | Prisma.CourtOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Courts.
   */
  cursor?: Prisma.CourtWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Courts.
   */
  distinct?: Prisma.CourtScalarFieldEnum | Prisma.CourtScalarFieldEnum[]
}

/**
 * Court findFirstOrThrow
 */
export type CourtFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter, which Court to fetch.
   */
  where?: Prisma.CourtWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courts to fetch.
   */
  orderBy?: Prisma.CourtOrderByWithRelationInput | Prisma.CourtOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Courts.
   */
  cursor?: Prisma.CourtWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Courts.
   */
  distinct?: Prisma.CourtScalarFieldEnum | Prisma.CourtScalarFieldEnum[]
}

/**
 * Court findMany
 */
export type CourtFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter, which Courts to fetch.
   */
  where?: Prisma.CourtWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Courts to fetch.
   */
  orderBy?: Prisma.CourtOrderByWithRelationInput | Prisma.CourtOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Courts.
   */
  cursor?: Prisma.CourtWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Courts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Courts.
   */
  skip?: number
  distinct?: Prisma.CourtScalarFieldEnum | Prisma.CourtScalarFieldEnum[]
}

/**
 * Court create
 */
export type CourtCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * The data needed to create a Court.
   */
  data: Prisma.XOR<Prisma.CourtCreateInput, Prisma.CourtUncheckedCreateInput>
}

/**
 * Court createMany
 */
export type CourtCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Courts.
   */
  data: Prisma.CourtCreateManyInput | Prisma.CourtCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Court createManyAndReturn
 */
export type CourtCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * The data used to create many Courts.
   */
  data: Prisma.CourtCreateManyInput | Prisma.CourtCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Court update
 */
export type CourtUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * The data needed to update a Court.
   */
  data: Prisma.XOR<Prisma.CourtUpdateInput, Prisma.CourtUncheckedUpdateInput>
  /**
   * Choose, which Court to update.
   */
  where: Prisma.CourtWhereUniqueInput
}

/**
 * Court updateMany
 */
export type CourtUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Courts.
   */
  data: Prisma.XOR<Prisma.CourtUpdateManyMutationInput, Prisma.CourtUncheckedUpdateManyInput>
  /**
   * Filter which Courts to update
   */
  where?: Prisma.CourtWhereInput
  /**
   * Limit how many Courts to update.
   */
  limit?: number
}

/**
 * Court updateManyAndReturn
 */
export type CourtUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * The data used to update Courts.
   */
  data: Prisma.XOR<Prisma.CourtUpdateManyMutationInput, Prisma.CourtUncheckedUpdateManyInput>
  /**
   * Filter which Courts to update
   */
  where?: Prisma.CourtWhereInput
  /**
   * Limit how many Courts to update.
   */
  limit?: number
}

/**
 * Court upsert
 */
export type CourtUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * The filter to search for the Court to update in case it exists.
   */
  where: Prisma.CourtWhereUniqueInput
  /**
   * In case the Court found by the `where` argument doesn't exist, create a new Court with this data.
   */
  create: Prisma.XOR<Prisma.CourtCreateInput, Prisma.CourtUncheckedCreateInput>
  /**
   * In case the Court was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CourtUpdateInput, Prisma.CourtUncheckedUpdateInput>
}

/**
 * Court delete
 */
export type CourtDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  /**
   * Filter which Court to delete.
   */
  where: Prisma.CourtWhereUniqueInput
}

/**
 * Court deleteMany
 */
export type CourtDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Courts to delete
   */
  where?: Prisma.CourtWhereInput
  /**
   * Limit how many Courts to delete.
   */
  limit?: number
}

/**
 * Court.cases
 */
export type Court$casesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  where?: Prisma.LegalCaseWhereInput
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  cursor?: Prisma.LegalCaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LegalCaseScalarFieldEnum | Prisma.LegalCaseScalarFieldEnum[]
}

/**
 * Court without action
 */
export type CourtDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
}
