
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LegalCase` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LegalCase
 * 
 */
export type LegalCaseModel = runtime.Types.Result.DefaultSelection<Prisma.$LegalCasePayload>

export type AggregateLegalCase = {
  _count: LegalCaseCountAggregateOutputType | null
  _min: LegalCaseMinAggregateOutputType | null
  _max: LegalCaseMaxAggregateOutputType | null
}

export type LegalCaseMinAggregateOutputType = {
  id: string | null
  caseNumber: string | null
  caseName: string | null
  slug: string | null
  summary: string | null
  parties: string | null
  plaintiff: string | null
  defendant: string | null
  judges: string | null
  verdict: string | null
  legalBasis: string | null
  caseDate: Date | null
  resolutionDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  courtId: string | null
  caseTypeId: string | null
  jurisdiction: $Enums.Jurisdiction | null
}

export type LegalCaseMaxAggregateOutputType = {
  id: string | null
  caseNumber: string | null
  caseName: string | null
  slug: string | null
  summary: string | null
  parties: string | null
  plaintiff: string | null
  defendant: string | null
  judges: string | null
  verdict: string | null
  legalBasis: string | null
  caseDate: Date | null
  resolutionDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  courtId: string | null
  caseTypeId: string | null
  jurisdiction: $Enums.Jurisdiction | null
}

export type LegalCaseCountAggregateOutputType = {
  id: number
  caseNumber: number
  caseName: number
  slug: number
  summary: number
  parties: number
  plaintiff: number
  defendant: number
  judges: number
  verdict: number
  legalBasis: number
  caseDate: number
  resolutionDate: number
  createdAt: number
  updatedAt: number
  courtId: number
  caseTypeId: number
  jurisdiction: number
  _all: number
}


export type LegalCaseMinAggregateInputType = {
  id?: true
  caseNumber?: true
  caseName?: true
  slug?: true
  summary?: true
  parties?: true
  plaintiff?: true
  defendant?: true
  judges?: true
  verdict?: true
  legalBasis?: true
  caseDate?: true
  resolutionDate?: true
  createdAt?: true
  updatedAt?: true
  courtId?: true
  caseTypeId?: true
  jurisdiction?: true
}

export type LegalCaseMaxAggregateInputType = {
  id?: true
  caseNumber?: true
  caseName?: true
  slug?: true
  summary?: true
  parties?: true
  plaintiff?: true
  defendant?: true
  judges?: true
  verdict?: true
  legalBasis?: true
  caseDate?: true
  resolutionDate?: true
  createdAt?: true
  updatedAt?: true
  courtId?: true
  caseTypeId?: true
  jurisdiction?: true
}

export type LegalCaseCountAggregateInputType = {
  id?: true
  caseNumber?: true
  caseName?: true
  slug?: true
  summary?: true
  parties?: true
  plaintiff?: true
  defendant?: true
  judges?: true
  verdict?: true
  legalBasis?: true
  caseDate?: true
  resolutionDate?: true
  createdAt?: true
  updatedAt?: true
  courtId?: true
  caseTypeId?: true
  jurisdiction?: true
  _all?: true
}

export type LegalCaseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LegalCase to aggregate.
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LegalCases to fetch.
   */
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LegalCaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LegalCases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LegalCases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LegalCases
  **/
  _count?: true | LegalCaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LegalCaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LegalCaseMaxAggregateInputType
}

export type GetLegalCaseAggregateType<T extends LegalCaseAggregateArgs> = {
      [P in keyof T & keyof AggregateLegalCase]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLegalCase[P]>
    : Prisma.GetScalarType<T[P], AggregateLegalCase[P]>
}




export type LegalCaseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LegalCaseWhereInput
  orderBy?: Prisma.LegalCaseOrderByWithAggregationInput | Prisma.LegalCaseOrderByWithAggregationInput[]
  by: Prisma.LegalCaseScalarFieldEnum[] | Prisma.LegalCaseScalarFieldEnum
  having?: Prisma.LegalCaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LegalCaseCountAggregateInputType | true
  _min?: LegalCaseMinAggregateInputType
  _max?: LegalCaseMaxAggregateInputType
}

export type LegalCaseGroupByOutputType = {
  id: string
  caseNumber: string
  caseName: string
  slug: string
  summary: string | null
  parties: string | null
  plaintiff: string | null
  defendant: string | null
  judges: string | null
  verdict: string | null
  legalBasis: string | null
  caseDate: Date | null
  resolutionDate: Date | null
  createdAt: Date
  updatedAt: Date
  courtId: string | null
  caseTypeId: string | null
  jurisdiction: $Enums.Jurisdiction | null
  _count: LegalCaseCountAggregateOutputType | null
  _min: LegalCaseMinAggregateOutputType | null
  _max: LegalCaseMaxAggregateOutputType | null
}

type GetLegalCaseGroupByPayload<T extends LegalCaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LegalCaseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LegalCaseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LegalCaseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LegalCaseGroupByOutputType[P]>
      }
    >
  >



export type LegalCaseWhereInput = {
  AND?: Prisma.LegalCaseWhereInput | Prisma.LegalCaseWhereInput[]
  OR?: Prisma.LegalCaseWhereInput[]
  NOT?: Prisma.LegalCaseWhereInput | Prisma.LegalCaseWhereInput[]
  id?: Prisma.StringFilter<"LegalCase"> | string
  caseNumber?: Prisma.StringFilter<"LegalCase"> | string
  caseName?: Prisma.StringFilter<"LegalCase"> | string
  slug?: Prisma.StringFilter<"LegalCase"> | string
  summary?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  parties?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  plaintiff?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  defendant?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  judges?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  verdict?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  legalBasis?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  resolutionDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  courtId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseTypeId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  jurisdiction?: Prisma.EnumJurisdictionNullableFilter<"LegalCase"> | $Enums.Jurisdiction | null
  court?: Prisma.XOR<Prisma.CourtNullableScalarRelationFilter, Prisma.CourtWhereInput> | null
  caseType?: Prisma.XOR<Prisma.CaseTypeNullableScalarRelationFilter, Prisma.CaseTypeWhereInput> | null
  articles?: Prisma.ArticleListRelationFilter
}

export type LegalCaseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  caseName?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  parties?: Prisma.SortOrderInput | Prisma.SortOrder
  plaintiff?: Prisma.SortOrderInput | Prisma.SortOrder
  defendant?: Prisma.SortOrderInput | Prisma.SortOrder
  judges?: Prisma.SortOrderInput | Prisma.SortOrder
  verdict?: Prisma.SortOrderInput | Prisma.SortOrder
  legalBasis?: Prisma.SortOrderInput | Prisma.SortOrder
  caseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  resolutionDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courtId?: Prisma.SortOrderInput | Prisma.SortOrder
  caseTypeId?: Prisma.SortOrderInput | Prisma.SortOrder
  jurisdiction?: Prisma.SortOrderInput | Prisma.SortOrder
  court?: Prisma.CourtOrderByWithRelationInput
  caseType?: Prisma.CaseTypeOrderByWithRelationInput
  articles?: Prisma.ArticleOrderByRelationAggregateInput
}

export type LegalCaseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  caseNumber?: string
  slug?: string
  AND?: Prisma.LegalCaseWhereInput | Prisma.LegalCaseWhereInput[]
  OR?: Prisma.LegalCaseWhereInput[]
  NOT?: Prisma.LegalCaseWhereInput | Prisma.LegalCaseWhereInput[]
  caseName?: Prisma.StringFilter<"LegalCase"> | string
  summary?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  parties?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  plaintiff?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  defendant?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  judges?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  verdict?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  legalBasis?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  resolutionDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  courtId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseTypeId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  jurisdiction?: Prisma.EnumJurisdictionNullableFilter<"LegalCase"> | $Enums.Jurisdiction | null
  court?: Prisma.XOR<Prisma.CourtNullableScalarRelationFilter, Prisma.CourtWhereInput> | null
  caseType?: Prisma.XOR<Prisma.CaseTypeNullableScalarRelationFilter, Prisma.CaseTypeWhereInput> | null
  articles?: Prisma.ArticleListRelationFilter
}, "id" | "caseNumber" | "slug">

export type LegalCaseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  caseName?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  parties?: Prisma.SortOrderInput | Prisma.SortOrder
  plaintiff?: Prisma.SortOrderInput | Prisma.SortOrder
  defendant?: Prisma.SortOrderInput | Prisma.SortOrder
  judges?: Prisma.SortOrderInput | Prisma.SortOrder
  verdict?: Prisma.SortOrderInput | Prisma.SortOrder
  legalBasis?: Prisma.SortOrderInput | Prisma.SortOrder
  caseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  resolutionDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courtId?: Prisma.SortOrderInput | Prisma.SortOrder
  caseTypeId?: Prisma.SortOrderInput | Prisma.SortOrder
  jurisdiction?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LegalCaseCountOrderByAggregateInput
  _max?: Prisma.LegalCaseMaxOrderByAggregateInput
  _min?: Prisma.LegalCaseMinOrderByAggregateInput
}

export type LegalCaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.LegalCaseScalarWhereWithAggregatesInput | Prisma.LegalCaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.LegalCaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LegalCaseScalarWhereWithAggregatesInput | Prisma.LegalCaseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LegalCase"> | string
  caseNumber?: Prisma.StringWithAggregatesFilter<"LegalCase"> | string
  caseName?: Prisma.StringWithAggregatesFilter<"LegalCase"> | string
  slug?: Prisma.StringWithAggregatesFilter<"LegalCase"> | string
  summary?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  parties?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  plaintiff?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  defendant?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  judges?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  verdict?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  legalBasis?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  caseDate?: Prisma.DateTimeNullableWithAggregatesFilter<"LegalCase"> | Date | string | null
  resolutionDate?: Prisma.DateTimeNullableWithAggregatesFilter<"LegalCase"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LegalCase"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LegalCase"> | Date | string
  courtId?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  caseTypeId?: Prisma.StringNullableWithAggregatesFilter<"LegalCase"> | string | null
  jurisdiction?: Prisma.EnumJurisdictionNullableWithAggregatesFilter<"LegalCase"> | $Enums.Jurisdiction | null
}

export type LegalCaseCreateInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  jurisdiction?: $Enums.Jurisdiction | null
  court?: Prisma.CourtCreateNestedOneWithoutCasesInput
  caseType?: Prisma.CaseTypeCreateNestedOneWithoutLegalCasesInput
  articles?: Prisma.ArticleCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseUncheckedCreateInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  courtId?: string | null
  caseTypeId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  court?: Prisma.CourtUpdateOneWithoutCasesNestedInput
  caseType?: Prisma.CaseTypeUpdateOneWithoutLegalCasesNestedInput
  articles?: Prisma.ArticleUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseCreateManyInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  courtId?: string | null
  caseTypeId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
}

export type LegalCaseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}

export type LegalCaseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}

export type LegalCaseListRelationFilter = {
  every?: Prisma.LegalCaseWhereInput
  some?: Prisma.LegalCaseWhereInput
  none?: Prisma.LegalCaseWhereInput
}

export type LegalCaseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LegalCaseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  caseName?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  parties?: Prisma.SortOrder
  plaintiff?: Prisma.SortOrder
  defendant?: Prisma.SortOrder
  judges?: Prisma.SortOrder
  verdict?: Prisma.SortOrder
  legalBasis?: Prisma.SortOrder
  caseDate?: Prisma.SortOrder
  resolutionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courtId?: Prisma.SortOrder
  caseTypeId?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
}

export type LegalCaseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  caseName?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  parties?: Prisma.SortOrder
  plaintiff?: Prisma.SortOrder
  defendant?: Prisma.SortOrder
  judges?: Prisma.SortOrder
  verdict?: Prisma.SortOrder
  legalBasis?: Prisma.SortOrder
  caseDate?: Prisma.SortOrder
  resolutionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courtId?: Prisma.SortOrder
  caseTypeId?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
}

export type LegalCaseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  caseName?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  parties?: Prisma.SortOrder
  plaintiff?: Prisma.SortOrder
  defendant?: Prisma.SortOrder
  judges?: Prisma.SortOrder
  verdict?: Prisma.SortOrder
  legalBasis?: Prisma.SortOrder
  caseDate?: Prisma.SortOrder
  resolutionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courtId?: Prisma.SortOrder
  caseTypeId?: Prisma.SortOrder
  jurisdiction?: Prisma.SortOrder
}

export type LegalCaseCreateNestedManyWithoutArticlesInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput> | Prisma.LegalCaseCreateWithoutArticlesInput[] | Prisma.LegalCaseUncheckedCreateWithoutArticlesInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutArticlesInput | Prisma.LegalCaseCreateOrConnectWithoutArticlesInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUncheckedCreateNestedManyWithoutArticlesInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput> | Prisma.LegalCaseCreateWithoutArticlesInput[] | Prisma.LegalCaseUncheckedCreateWithoutArticlesInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutArticlesInput | Prisma.LegalCaseCreateOrConnectWithoutArticlesInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUpdateManyWithoutArticlesNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput> | Prisma.LegalCaseCreateWithoutArticlesInput[] | Prisma.LegalCaseUncheckedCreateWithoutArticlesInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutArticlesInput | Prisma.LegalCaseCreateOrConnectWithoutArticlesInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutArticlesInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutArticlesInput[]
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutArticlesInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutArticlesInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutArticlesInput | Prisma.LegalCaseUpdateManyWithWhereWithoutArticlesInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type LegalCaseUncheckedUpdateManyWithoutArticlesNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput> | Prisma.LegalCaseCreateWithoutArticlesInput[] | Prisma.LegalCaseUncheckedCreateWithoutArticlesInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutArticlesInput | Prisma.LegalCaseCreateOrConnectWithoutArticlesInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutArticlesInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutArticlesInput[]
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutArticlesInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutArticlesInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutArticlesInput | Prisma.LegalCaseUpdateManyWithWhereWithoutArticlesInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type NullableEnumJurisdictionFieldUpdateOperationsInput = {
  set?: $Enums.Jurisdiction | null
}

export type LegalCaseCreateNestedManyWithoutCourtInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput> | Prisma.LegalCaseCreateWithoutCourtInput[] | Prisma.LegalCaseUncheckedCreateWithoutCourtInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCourtInput | Prisma.LegalCaseCreateOrConnectWithoutCourtInput[]
  createMany?: Prisma.LegalCaseCreateManyCourtInputEnvelope
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUncheckedCreateNestedManyWithoutCourtInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput> | Prisma.LegalCaseCreateWithoutCourtInput[] | Prisma.LegalCaseUncheckedCreateWithoutCourtInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCourtInput | Prisma.LegalCaseCreateOrConnectWithoutCourtInput[]
  createMany?: Prisma.LegalCaseCreateManyCourtInputEnvelope
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUpdateManyWithoutCourtNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput> | Prisma.LegalCaseCreateWithoutCourtInput[] | Prisma.LegalCaseUncheckedCreateWithoutCourtInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCourtInput | Prisma.LegalCaseCreateOrConnectWithoutCourtInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutCourtInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutCourtInput[]
  createMany?: Prisma.LegalCaseCreateManyCourtInputEnvelope
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutCourtInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutCourtInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutCourtInput | Prisma.LegalCaseUpdateManyWithWhereWithoutCourtInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type LegalCaseUncheckedUpdateManyWithoutCourtNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput> | Prisma.LegalCaseCreateWithoutCourtInput[] | Prisma.LegalCaseUncheckedCreateWithoutCourtInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCourtInput | Prisma.LegalCaseCreateOrConnectWithoutCourtInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutCourtInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutCourtInput[]
  createMany?: Prisma.LegalCaseCreateManyCourtInputEnvelope
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutCourtInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutCourtInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutCourtInput | Prisma.LegalCaseUpdateManyWithWhereWithoutCourtInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type LegalCaseCreateNestedManyWithoutCaseTypeInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput> | Prisma.LegalCaseCreateWithoutCaseTypeInput[] | Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput | Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput[]
  createMany?: Prisma.LegalCaseCreateManyCaseTypeInputEnvelope
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUncheckedCreateNestedManyWithoutCaseTypeInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput> | Prisma.LegalCaseCreateWithoutCaseTypeInput[] | Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput | Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput[]
  createMany?: Prisma.LegalCaseCreateManyCaseTypeInputEnvelope
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
}

export type LegalCaseUpdateManyWithoutCaseTypeNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput> | Prisma.LegalCaseCreateWithoutCaseTypeInput[] | Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput | Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutCaseTypeInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutCaseTypeInput[]
  createMany?: Prisma.LegalCaseCreateManyCaseTypeInputEnvelope
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutCaseTypeInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutCaseTypeInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutCaseTypeInput | Prisma.LegalCaseUpdateManyWithWhereWithoutCaseTypeInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type LegalCaseUncheckedUpdateManyWithoutCaseTypeNestedInput = {
  create?: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput> | Prisma.LegalCaseCreateWithoutCaseTypeInput[] | Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput[]
  connectOrCreate?: Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput | Prisma.LegalCaseCreateOrConnectWithoutCaseTypeInput[]
  upsert?: Prisma.LegalCaseUpsertWithWhereUniqueWithoutCaseTypeInput | Prisma.LegalCaseUpsertWithWhereUniqueWithoutCaseTypeInput[]
  createMany?: Prisma.LegalCaseCreateManyCaseTypeInputEnvelope
  set?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  disconnect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  delete?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  connect?: Prisma.LegalCaseWhereUniqueInput | Prisma.LegalCaseWhereUniqueInput[]
  update?: Prisma.LegalCaseUpdateWithWhereUniqueWithoutCaseTypeInput | Prisma.LegalCaseUpdateWithWhereUniqueWithoutCaseTypeInput[]
  updateMany?: Prisma.LegalCaseUpdateManyWithWhereWithoutCaseTypeInput | Prisma.LegalCaseUpdateManyWithWhereWithoutCaseTypeInput[]
  deleteMany?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
}

export type LegalCaseCreateWithoutArticlesInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  jurisdiction?: $Enums.Jurisdiction | null
  court?: Prisma.CourtCreateNestedOneWithoutCasesInput
  caseType?: Prisma.CaseTypeCreateNestedOneWithoutLegalCasesInput
}

export type LegalCaseUncheckedCreateWithoutArticlesInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  courtId?: string | null
  caseTypeId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
}

export type LegalCaseCreateOrConnectWithoutArticlesInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput>
}

export type LegalCaseUpsertWithWhereUniqueWithoutArticlesInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LegalCaseUpdateWithoutArticlesInput, Prisma.LegalCaseUncheckedUpdateWithoutArticlesInput>
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutArticlesInput, Prisma.LegalCaseUncheckedCreateWithoutArticlesInput>
}

export type LegalCaseUpdateWithWhereUniqueWithoutArticlesInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateWithoutArticlesInput, Prisma.LegalCaseUncheckedUpdateWithoutArticlesInput>
}

export type LegalCaseUpdateManyWithWhereWithoutArticlesInput = {
  where: Prisma.LegalCaseScalarWhereInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateManyMutationInput, Prisma.LegalCaseUncheckedUpdateManyWithoutArticlesInput>
}

export type LegalCaseScalarWhereInput = {
  AND?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
  OR?: Prisma.LegalCaseScalarWhereInput[]
  NOT?: Prisma.LegalCaseScalarWhereInput | Prisma.LegalCaseScalarWhereInput[]
  id?: Prisma.StringFilter<"LegalCase"> | string
  caseNumber?: Prisma.StringFilter<"LegalCase"> | string
  caseName?: Prisma.StringFilter<"LegalCase"> | string
  slug?: Prisma.StringFilter<"LegalCase"> | string
  summary?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  parties?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  plaintiff?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  defendant?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  judges?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  verdict?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  legalBasis?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  resolutionDate?: Prisma.DateTimeNullableFilter<"LegalCase"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LegalCase"> | Date | string
  courtId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  caseTypeId?: Prisma.StringNullableFilter<"LegalCase"> | string | null
  jurisdiction?: Prisma.EnumJurisdictionNullableFilter<"LegalCase"> | $Enums.Jurisdiction | null
}

export type LegalCaseCreateWithoutCourtInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  jurisdiction?: $Enums.Jurisdiction | null
  caseType?: Prisma.CaseTypeCreateNestedOneWithoutLegalCasesInput
  articles?: Prisma.ArticleCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseUncheckedCreateWithoutCourtInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  caseTypeId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseCreateOrConnectWithoutCourtInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput>
}

export type LegalCaseCreateManyCourtInputEnvelope = {
  data: Prisma.LegalCaseCreateManyCourtInput | Prisma.LegalCaseCreateManyCourtInput[]
  skipDuplicates?: boolean
}

export type LegalCaseUpsertWithWhereUniqueWithoutCourtInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LegalCaseUpdateWithoutCourtInput, Prisma.LegalCaseUncheckedUpdateWithoutCourtInput>
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutCourtInput, Prisma.LegalCaseUncheckedCreateWithoutCourtInput>
}

export type LegalCaseUpdateWithWhereUniqueWithoutCourtInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateWithoutCourtInput, Prisma.LegalCaseUncheckedUpdateWithoutCourtInput>
}

export type LegalCaseUpdateManyWithWhereWithoutCourtInput = {
  where: Prisma.LegalCaseScalarWhereInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateManyMutationInput, Prisma.LegalCaseUncheckedUpdateManyWithoutCourtInput>
}

export type LegalCaseCreateWithoutCaseTypeInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  jurisdiction?: $Enums.Jurisdiction | null
  court?: Prisma.CourtCreateNestedOneWithoutCasesInput
  articles?: Prisma.ArticleCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseUncheckedCreateWithoutCaseTypeInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  courtId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedCreateNestedManyWithoutLegalCasesInput
}

export type LegalCaseCreateOrConnectWithoutCaseTypeInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput>
}

export type LegalCaseCreateManyCaseTypeInputEnvelope = {
  data: Prisma.LegalCaseCreateManyCaseTypeInput | Prisma.LegalCaseCreateManyCaseTypeInput[]
  skipDuplicates?: boolean
}

export type LegalCaseUpsertWithWhereUniqueWithoutCaseTypeInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LegalCaseUpdateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedUpdateWithoutCaseTypeInput>
  create: Prisma.XOR<Prisma.LegalCaseCreateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedCreateWithoutCaseTypeInput>
}

export type LegalCaseUpdateWithWhereUniqueWithoutCaseTypeInput = {
  where: Prisma.LegalCaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateWithoutCaseTypeInput, Prisma.LegalCaseUncheckedUpdateWithoutCaseTypeInput>
}

export type LegalCaseUpdateManyWithWhereWithoutCaseTypeInput = {
  where: Prisma.LegalCaseScalarWhereInput
  data: Prisma.XOR<Prisma.LegalCaseUpdateManyMutationInput, Prisma.LegalCaseUncheckedUpdateManyWithoutCaseTypeInput>
}

export type LegalCaseUpdateWithoutArticlesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  court?: Prisma.CourtUpdateOneWithoutCasesNestedInput
  caseType?: Prisma.CaseTypeUpdateOneWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateWithoutArticlesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}

export type LegalCaseUncheckedUpdateManyWithoutArticlesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}

export type LegalCaseCreateManyCourtInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  caseTypeId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
}

export type LegalCaseUpdateWithoutCourtInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  caseType?: Prisma.CaseTypeUpdateOneWithoutLegalCasesNestedInput
  articles?: Prisma.ArticleUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateWithoutCourtInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateManyWithoutCourtInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  caseTypeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}

export type LegalCaseCreateManyCaseTypeInput = {
  id?: string
  caseNumber: string
  caseName: string
  slug: string
  summary?: string | null
  parties?: string | null
  plaintiff?: string | null
  defendant?: string | null
  judges?: string | null
  verdict?: string | null
  legalBasis?: string | null
  caseDate?: Date | string | null
  resolutionDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  courtId?: string | null
  jurisdiction?: $Enums.Jurisdiction | null
}

export type LegalCaseUpdateWithoutCaseTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  court?: Prisma.CourtUpdateOneWithoutCasesNestedInput
  articles?: Prisma.ArticleUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateWithoutCaseTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
  articles?: Prisma.ArticleUncheckedUpdateManyWithoutLegalCasesNestedInput
}

export type LegalCaseUncheckedUpdateManyWithoutCaseTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  caseName?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parties?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plaintiff?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defendant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  judges?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verdict?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  legalBasis?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courtId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jurisdiction?: Prisma.NullableEnumJurisdictionFieldUpdateOperationsInput | $Enums.Jurisdiction | null
}


/**
 * Count Type LegalCaseCountOutputType
 */

export type LegalCaseCountOutputType = {
  articles: number
}

export type LegalCaseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  articles?: boolean | LegalCaseCountOutputTypeCountArticlesArgs
}

/**
 * LegalCaseCountOutputType without action
 */
export type LegalCaseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCaseCountOutputType
   */
  select?: Prisma.LegalCaseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LegalCaseCountOutputType without action
 */
export type LegalCaseCountOutputTypeCountArticlesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArticleWhereInput
}


export type LegalCaseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caseNumber?: boolean
  caseName?: boolean
  slug?: boolean
  summary?: boolean
  parties?: boolean
  plaintiff?: boolean
  defendant?: boolean
  judges?: boolean
  verdict?: boolean
  legalBasis?: boolean
  caseDate?: boolean
  resolutionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courtId?: boolean
  caseTypeId?: boolean
  jurisdiction?: boolean
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
  articles?: boolean | Prisma.LegalCase$articlesArgs<ExtArgs>
  _count?: boolean | Prisma.LegalCaseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["legalCase"]>

export type LegalCaseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caseNumber?: boolean
  caseName?: boolean
  slug?: boolean
  summary?: boolean
  parties?: boolean
  plaintiff?: boolean
  defendant?: boolean
  judges?: boolean
  verdict?: boolean
  legalBasis?: boolean
  caseDate?: boolean
  resolutionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courtId?: boolean
  caseTypeId?: boolean
  jurisdiction?: boolean
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
}, ExtArgs["result"]["legalCase"]>

export type LegalCaseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  caseNumber?: boolean
  caseName?: boolean
  slug?: boolean
  summary?: boolean
  parties?: boolean
  plaintiff?: boolean
  defendant?: boolean
  judges?: boolean
  verdict?: boolean
  legalBasis?: boolean
  caseDate?: boolean
  resolutionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courtId?: boolean
  caseTypeId?: boolean
  jurisdiction?: boolean
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
}, ExtArgs["result"]["legalCase"]>

export type LegalCaseSelectScalar = {
  id?: boolean
  caseNumber?: boolean
  caseName?: boolean
  slug?: boolean
  summary?: boolean
  parties?: boolean
  plaintiff?: boolean
  defendant?: boolean
  judges?: boolean
  verdict?: boolean
  legalBasis?: boolean
  caseDate?: boolean
  resolutionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courtId?: boolean
  caseTypeId?: boolean
  jurisdiction?: boolean
}

export type LegalCaseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "caseNumber" | "caseName" | "slug" | "summary" | "parties" | "plaintiff" | "defendant" | "judges" | "verdict" | "legalBasis" | "caseDate" | "resolutionDate" | "createdAt" | "updatedAt" | "courtId" | "caseTypeId" | "jurisdiction", ExtArgs["result"]["legalCase"]>
export type LegalCaseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
  articles?: boolean | Prisma.LegalCase$articlesArgs<ExtArgs>
  _count?: boolean | Prisma.LegalCaseCountOutputTypeDefaultArgs<ExtArgs>
}
export type LegalCaseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
}
export type LegalCaseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  court?: boolean | Prisma.LegalCase$courtArgs<ExtArgs>
  caseType?: boolean | Prisma.LegalCase$caseTypeArgs<ExtArgs>
}

export type $LegalCasePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LegalCase"
  objects: {
    court: Prisma.$CourtPayload<ExtArgs> | null
    caseType: Prisma.$CaseTypePayload<ExtArgs> | null
    articles: Prisma.$ArticlePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    caseNumber: string
    caseName: string
    slug: string
    summary: string | null
    parties: string | null
    plaintiff: string | null
    defendant: string | null
    judges: string | null
    verdict: string | null
    legalBasis: string | null
    caseDate: Date | null
    resolutionDate: Date | null
    createdAt: Date
    updatedAt: Date
    courtId: string | null
    caseTypeId: string | null
    jurisdiction: $Enums.Jurisdiction | null
  }, ExtArgs["result"]["legalCase"]>
  composites: {}
}

export type LegalCaseGetPayload<S extends boolean | null | undefined | LegalCaseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LegalCasePayload, S>

export type LegalCaseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LegalCaseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LegalCaseCountAggregateInputType | true
  }

export interface LegalCaseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LegalCase'], meta: { name: 'LegalCase' } }
  /**
   * Find zero or one LegalCase that matches the filter.
   * @param {LegalCaseFindUniqueArgs} args - Arguments to find a LegalCase
   * @example
   * // Get one LegalCase
   * const legalCase = await prisma.legalCase.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LegalCaseFindUniqueArgs>(args: Prisma.SelectSubset<T, LegalCaseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LegalCase that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LegalCaseFindUniqueOrThrowArgs} args - Arguments to find a LegalCase
   * @example
   * // Get one LegalCase
   * const legalCase = await prisma.legalCase.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LegalCaseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LegalCaseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LegalCase that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseFindFirstArgs} args - Arguments to find a LegalCase
   * @example
   * // Get one LegalCase
   * const legalCase = await prisma.legalCase.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LegalCaseFindFirstArgs>(args?: Prisma.SelectSubset<T, LegalCaseFindFirstArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LegalCase that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseFindFirstOrThrowArgs} args - Arguments to find a LegalCase
   * @example
   * // Get one LegalCase
   * const legalCase = await prisma.legalCase.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LegalCaseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LegalCaseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LegalCases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LegalCases
   * const legalCases = await prisma.legalCase.findMany()
   * 
   * // Get first 10 LegalCases
   * const legalCases = await prisma.legalCase.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const legalCaseWithIdOnly = await prisma.legalCase.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LegalCaseFindManyArgs>(args?: Prisma.SelectSubset<T, LegalCaseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LegalCase.
   * @param {LegalCaseCreateArgs} args - Arguments to create a LegalCase.
   * @example
   * // Create one LegalCase
   * const LegalCase = await prisma.legalCase.create({
   *   data: {
   *     // ... data to create a LegalCase
   *   }
   * })
   * 
   */
  create<T extends LegalCaseCreateArgs>(args: Prisma.SelectSubset<T, LegalCaseCreateArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LegalCases.
   * @param {LegalCaseCreateManyArgs} args - Arguments to create many LegalCases.
   * @example
   * // Create many LegalCases
   * const legalCase = await prisma.legalCase.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LegalCaseCreateManyArgs>(args?: Prisma.SelectSubset<T, LegalCaseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LegalCases and returns the data saved in the database.
   * @param {LegalCaseCreateManyAndReturnArgs} args - Arguments to create many LegalCases.
   * @example
   * // Create many LegalCases
   * const legalCase = await prisma.legalCase.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LegalCases and only return the `id`
   * const legalCaseWithIdOnly = await prisma.legalCase.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LegalCaseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LegalCaseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LegalCase.
   * @param {LegalCaseDeleteArgs} args - Arguments to delete one LegalCase.
   * @example
   * // Delete one LegalCase
   * const LegalCase = await prisma.legalCase.delete({
   *   where: {
   *     // ... filter to delete one LegalCase
   *   }
   * })
   * 
   */
  delete<T extends LegalCaseDeleteArgs>(args: Prisma.SelectSubset<T, LegalCaseDeleteArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LegalCase.
   * @param {LegalCaseUpdateArgs} args - Arguments to update one LegalCase.
   * @example
   * // Update one LegalCase
   * const legalCase = await prisma.legalCase.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LegalCaseUpdateArgs>(args: Prisma.SelectSubset<T, LegalCaseUpdateArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LegalCases.
   * @param {LegalCaseDeleteManyArgs} args - Arguments to filter LegalCases to delete.
   * @example
   * // Delete a few LegalCases
   * const { count } = await prisma.legalCase.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LegalCaseDeleteManyArgs>(args?: Prisma.SelectSubset<T, LegalCaseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LegalCases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LegalCases
   * const legalCase = await prisma.legalCase.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LegalCaseUpdateManyArgs>(args: Prisma.SelectSubset<T, LegalCaseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LegalCases and returns the data updated in the database.
   * @param {LegalCaseUpdateManyAndReturnArgs} args - Arguments to update many LegalCases.
   * @example
   * // Update many LegalCases
   * const legalCase = await prisma.legalCase.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LegalCases and only return the `id`
   * const legalCaseWithIdOnly = await prisma.legalCase.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LegalCaseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LegalCaseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LegalCase.
   * @param {LegalCaseUpsertArgs} args - Arguments to update or create a LegalCase.
   * @example
   * // Update or create a LegalCase
   * const legalCase = await prisma.legalCase.upsert({
   *   create: {
   *     // ... data to create a LegalCase
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LegalCase we want to update
   *   }
   * })
   */
  upsert<T extends LegalCaseUpsertArgs>(args: Prisma.SelectSubset<T, LegalCaseUpsertArgs<ExtArgs>>): Prisma.Prisma__LegalCaseClient<runtime.Types.Result.GetResult<Prisma.$LegalCasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LegalCases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseCountArgs} args - Arguments to filter LegalCases to count.
   * @example
   * // Count the number of LegalCases
   * const count = await prisma.legalCase.count({
   *   where: {
   *     // ... the filter for the LegalCases we want to count
   *   }
   * })
  **/
  count<T extends LegalCaseCountArgs>(
    args?: Prisma.Subset<T, LegalCaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LegalCaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LegalCase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LegalCaseAggregateArgs>(args: Prisma.Subset<T, LegalCaseAggregateArgs>): Prisma.PrismaPromise<GetLegalCaseAggregateType<T>>

  /**
   * Group by LegalCase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LegalCaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LegalCaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LegalCaseGroupByArgs['orderBy'] }
      : { orderBy?: LegalCaseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LegalCaseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLegalCaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LegalCase model
 */
readonly fields: LegalCaseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LegalCase.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LegalCaseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  court<T extends Prisma.LegalCase$courtArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LegalCase$courtArgs<ExtArgs>>): Prisma.Prisma__CourtClient<runtime.Types.Result.GetResult<Prisma.$CourtPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  caseType<T extends Prisma.LegalCase$caseTypeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LegalCase$caseTypeArgs<ExtArgs>>): Prisma.Prisma__CaseTypeClient<runtime.Types.Result.GetResult<Prisma.$CaseTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  articles<T extends Prisma.LegalCase$articlesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LegalCase$articlesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArticlePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LegalCase model
 */
export interface LegalCaseFieldRefs {
  readonly id: Prisma.FieldRef<"LegalCase", 'String'>
  readonly caseNumber: Prisma.FieldRef<"LegalCase", 'String'>
  readonly caseName: Prisma.FieldRef<"LegalCase", 'String'>
  readonly slug: Prisma.FieldRef<"LegalCase", 'String'>
  readonly summary: Prisma.FieldRef<"LegalCase", 'String'>
  readonly parties: Prisma.FieldRef<"LegalCase", 'String'>
  readonly plaintiff: Prisma.FieldRef<"LegalCase", 'String'>
  readonly defendant: Prisma.FieldRef<"LegalCase", 'String'>
  readonly judges: Prisma.FieldRef<"LegalCase", 'String'>
  readonly verdict: Prisma.FieldRef<"LegalCase", 'String'>
  readonly legalBasis: Prisma.FieldRef<"LegalCase", 'String'>
  readonly caseDate: Prisma.FieldRef<"LegalCase", 'DateTime'>
  readonly resolutionDate: Prisma.FieldRef<"LegalCase", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"LegalCase", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LegalCase", 'DateTime'>
  readonly courtId: Prisma.FieldRef<"LegalCase", 'String'>
  readonly caseTypeId: Prisma.FieldRef<"LegalCase", 'String'>
  readonly jurisdiction: Prisma.FieldRef<"LegalCase", 'Jurisdiction'>
}
    

// Custom InputTypes
/**
 * LegalCase findUnique
 */
export type LegalCaseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter, which LegalCase to fetch.
   */
  where: Prisma.LegalCaseWhereUniqueInput
}

/**
 * LegalCase findUniqueOrThrow
 */
export type LegalCaseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter, which LegalCase to fetch.
   */
  where: Prisma.LegalCaseWhereUniqueInput
}

/**
 * LegalCase findFirst
 */
export type LegalCaseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter, which LegalCase to fetch.
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LegalCases to fetch.
   */
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LegalCases.
   */
  cursor?: Prisma.LegalCaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LegalCases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LegalCases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LegalCases.
   */
  distinct?: Prisma.LegalCaseScalarFieldEnum | Prisma.LegalCaseScalarFieldEnum[]
}

/**
 * LegalCase findFirstOrThrow
 */
export type LegalCaseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter, which LegalCase to fetch.
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LegalCases to fetch.
   */
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LegalCases.
   */
  cursor?: Prisma.LegalCaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LegalCases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LegalCases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LegalCases.
   */
  distinct?: Prisma.LegalCaseScalarFieldEnum | Prisma.LegalCaseScalarFieldEnum[]
}

/**
 * LegalCase findMany
 */
export type LegalCaseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter, which LegalCases to fetch.
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LegalCases to fetch.
   */
  orderBy?: Prisma.LegalCaseOrderByWithRelationInput | Prisma.LegalCaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LegalCases.
   */
  cursor?: Prisma.LegalCaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LegalCases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LegalCases.
   */
  skip?: number
  distinct?: Prisma.LegalCaseScalarFieldEnum | Prisma.LegalCaseScalarFieldEnum[]
}

/**
 * LegalCase create
 */
export type LegalCaseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * The data needed to create a LegalCase.
   */
  data: Prisma.XOR<Prisma.LegalCaseCreateInput, Prisma.LegalCaseUncheckedCreateInput>
}

/**
 * LegalCase createMany
 */
export type LegalCaseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LegalCases.
   */
  data: Prisma.LegalCaseCreateManyInput | Prisma.LegalCaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LegalCase createManyAndReturn
 */
export type LegalCaseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * The data used to create many LegalCases.
   */
  data: Prisma.LegalCaseCreateManyInput | Prisma.LegalCaseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LegalCase update
 */
export type LegalCaseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * The data needed to update a LegalCase.
   */
  data: Prisma.XOR<Prisma.LegalCaseUpdateInput, Prisma.LegalCaseUncheckedUpdateInput>
  /**
   * Choose, which LegalCase to update.
   */
  where: Prisma.LegalCaseWhereUniqueInput
}

/**
 * LegalCase updateMany
 */
export type LegalCaseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LegalCases.
   */
  data: Prisma.XOR<Prisma.LegalCaseUpdateManyMutationInput, Prisma.LegalCaseUncheckedUpdateManyInput>
  /**
   * Filter which LegalCases to update
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * Limit how many LegalCases to update.
   */
  limit?: number
}

/**
 * LegalCase updateManyAndReturn
 */
export type LegalCaseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * The data used to update LegalCases.
   */
  data: Prisma.XOR<Prisma.LegalCaseUpdateManyMutationInput, Prisma.LegalCaseUncheckedUpdateManyInput>
  /**
   * Filter which LegalCases to update
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * Limit how many LegalCases to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LegalCase upsert
 */
export type LegalCaseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * The filter to search for the LegalCase to update in case it exists.
   */
  where: Prisma.LegalCaseWhereUniqueInput
  /**
   * In case the LegalCase found by the `where` argument doesn't exist, create a new LegalCase with this data.
   */
  create: Prisma.XOR<Prisma.LegalCaseCreateInput, Prisma.LegalCaseUncheckedCreateInput>
  /**
   * In case the LegalCase was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LegalCaseUpdateInput, Prisma.LegalCaseUncheckedUpdateInput>
}

/**
 * LegalCase delete
 */
export type LegalCaseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
  /**
   * Filter which LegalCase to delete.
   */
  where: Prisma.LegalCaseWhereUniqueInput
}

/**
 * LegalCase deleteMany
 */
export type LegalCaseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LegalCases to delete
   */
  where?: Prisma.LegalCaseWhereInput
  /**
   * Limit how many LegalCases to delete.
   */
  limit?: number
}

/**
 * LegalCase.court
 */
export type LegalCase$courtArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Court
   */
  select?: Prisma.CourtSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Court
   */
  omit?: Prisma.CourtOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourtInclude<ExtArgs> | null
  where?: Prisma.CourtWhereInput
}

/**
 * LegalCase.caseType
 */
export type LegalCase$caseTypeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CaseType
   */
  select?: Prisma.CaseTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CaseType
   */
  omit?: Prisma.CaseTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseTypeInclude<ExtArgs> | null
  where?: Prisma.CaseTypeWhereInput
}

/**
 * LegalCase.articles
 */
export type LegalCase$articlesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Article
   */
  select?: Prisma.ArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Article
   */
  omit?: Prisma.ArticleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArticleInclude<ExtArgs> | null
  where?: Prisma.ArticleWhereInput
  orderBy?: Prisma.ArticleOrderByWithRelationInput | Prisma.ArticleOrderByWithRelationInput[]
  cursor?: Prisma.ArticleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ArticleScalarFieldEnum | Prisma.ArticleScalarFieldEnum[]
}

/**
 * LegalCase without action
 */
export type LegalCaseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LegalCase
   */
  select?: Prisma.LegalCaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LegalCase
   */
  omit?: Prisma.LegalCaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LegalCaseInclude<ExtArgs> | null
}
