query RecentArticles($take: Int, $skip: Int, $filter: ArticleFilter) {
  articles(take: $take, skip: $skip, filter: $filter) {
    items {
      id
      title
      slug
      excerpt
      publishedAt
      readingTimeMin
      views
      author {
        id
        name
        image
      }
      featuredImage {
        id
        url
        alt
      }
      categories {
        id
        name
        slug
      }
      tags {
        id
        name
        slug
      }
    }
    pageInfo {
      totalCount
      hasNextPage
      hasPreviousPage
    }
  }
}
