http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      service: api
      entryPoints:
        - web
      priority: 10

    storage:
      rule: "PathPrefix(`/crop-media`)"
      service: storage
      entryPoints:
        - web
      priority: 10

    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
      priority: 1

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:7000"

    storage:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3900"

    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
