query Medias($take: Int, $skip: Int, $filter: MediaFilter) {
  medias(take: $take, skip: $skip, filter: $filter) {
    items {
      id
      objectKey
      url
      alt
      type
      size
      mimeType
      filename
      createdAt
      updatedAt
      uploader {
        id
        name
        email
        image
      }
    }
    pageInfo {
      totalCount
      hasNextPage
      hasPreviousPage
    }
  }
}

query Media($id: String!) {
  media(id: $id) {
    id
    objectKey
    url
    alt
    type
    size
    mimeType
    filename
    createdAt
    updatedAt
    uploader {
      id
      name
      email
      image
    }
  }
}
