
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  PUBLIC: 'PUBLIC',
  COLLABORATOR: 'COLLABORATOR',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const MediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  FILE: 'FILE'
} as const

export type MediaType = (typeof MediaType)[keyof typeof MediaType]


export const ArticleStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
} as const

export type ArticleStatus = (typeof ArticleStatus)[keyof typeof ArticleStatus]


export const Jurisdiction = {
  NACIONAL: 'NACIONAL',
  REGIONAL: 'REGIONAL',
  LOCAL: 'LOCAL',
  INTERNACIONAL: 'INTERNACIONAL'
} as const

export type Jurisdiction = (typeof Jurisdiction)[keyof typeof Jurisdiction]


export const CaseType = {
  CIVIL: 'CIVIL',
  PENAL: 'PENAL',
  CONSTITUCIONAL: 'CONSTITUCIONAL',
  LABORAL: 'LABORAL',
  ADMINISTRATIVO: 'ADMINISTRATIVO',
  COMERCIAL: 'COMERCIAL',
  FAMILIA: 'FAMILIA',
  TRIBUTARIO: 'TRIBUTARIO',
  AMBIENTAL: 'AMBIENTAL'
} as const

export type CaseType = (typeof CaseType)[keyof typeof CaseType]


export const CourtType = {
  SUPREMA: 'SUPREMA',
  SUPERIOR: 'SUPERIOR',
  PRIMERA_INSTANCIA: 'PRIMERA_INSTANCIA',
  ESPECIALIZADA: 'ESPECIALIZADA',
  CONSTITUCIONAL: 'CONSTITUCIONAL'
} as const

export type CourtType = (typeof CourtType)[keyof typeof CourtType]
