query Medias($take: Int, $skip: Int, $search: String) {
  medias(take: $take, skip: $skip, search: $search) {
    id
    objectKey
    url
    alt
    type
    size
    mimeType
    filename
    createdAt
    updatedAt
    uploader {
      id
      name
      email
      image
    }
  }
}

query Media($id: String!) {
  media(id: $id) {
    id
    objectKey
    url
    alt
    type
    size
    mimeType
    filename
    createdAt
    updatedAt
    uploader {
      id
      name
      email
      image
    }
  }
}
